import type { Student, Registration, ContactMessage, Course } from '@/types';

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'STU-001',
    fullName: 'Maria Santos',
    email: 'maria@example.com',
    mobile: '09171234567',
    facebook: 'fb.com/mariasantos',
    address: 'Mandaue City, Cebu',
    experience: 'beginner',
    preferredSchedule: 'wednesday',
    referralCode: 'PHIL-MRS001',
    sponsorCode: '',
    paymentMethod: 'gcash',
    paymentReference: 'GC-123456789',
    status: 'next_course_qualified',
    registeredAt: '2026-04-15T08:00:00Z',
    approvedAt: '2026-04-16T09:00:00Z',
    directReferrals: ['STU-002', 'STU-003', 'STU-004'],
    secondLevelReferrals: ['STU-005', 'STU-006'],
    basicCourseStatus: 'completed',
    nextCourseStatus: 'in_progress',
    finalCourseStatus: 'locked',
    challengeTrainingStatus: 'not_started',
    challengeProfirmStatus: 'not_started',
    certificateIssued: false,
    awardStatus: 'not_qualified',
    basicCourseProgress: 100,
    nextCourseProgress: 45,
    finalCourseProgress: 0,
  },
  {
    id: 'STU-002',
    fullName: 'Juan dela Cruz',
    email: 'juan@example.com',
    mobile: '09281234567',
    facebook: 'fb.com/juandelacruz',
    address: 'Cebu City',
    experience: 'intermediate',
    preferredSchedule: 'saturday',
    referralCode: 'PHIL-JDC002',
    sponsorCode: 'PHIL-MRS001',
    sponsorId: 'STU-001',
    paymentMethod: 'bank_transfer',
    paymentReference: 'BT-987654321',
    status: 'basic_course',
    registeredAt: '2026-04-20T10:00:00Z',
    approvedAt: '2026-04-21T11:00:00Z',
    directReferrals: ['STU-005'],
    secondLevelReferrals: [],
    basicCourseStatus: 'in_progress',
    nextCourseStatus: 'locked',
    finalCourseStatus: 'locked',
    challengeTrainingStatus: 'not_started',
    challengeProfirmStatus: 'not_started',
    certificateIssued: false,
    awardStatus: 'not_qualified',
    basicCourseProgress: 60,
    nextCourseProgress: 0,
    finalCourseProgress: 0,
  },
  {
    id: 'STU-003',
    fullName: 'Ana Reyes',
    email: 'ana@example.com',
    mobile: '09391234567',
    facebook: 'fb.com/anareyes',
    address: 'Lapu-Lapu City, Cebu',
    experience: 'beginner',
    preferredSchedule: 'wednesday',
    referralCode: 'PHIL-ARY003',
    sponsorCode: 'PHIL-MRS001',
    sponsorId: 'STU-001',
    paymentMethod: 'gcash',
    paymentReference: 'GC-111222333',
    status: 'challenge_training',
    registeredAt: '2026-03-10T14:00:00Z',
    approvedAt: '2026-03-11T09:00:00Z',
    directReferrals: ['STU-006', 'STU-007', 'STU-008'],
    secondLevelReferrals: [],
    basicCourseStatus: 'completed',
    nextCourseStatus: 'completed',
    finalCourseStatus: 'completed',
    challengeTrainingStatus: 'active',
    challengeProfirmStatus: 'not_started',
    certificateIssued: false,
    awardStatus: 'not_qualified',
    basicCourseProgress: 100,
    nextCourseProgress: 100,
    finalCourseProgress: 100,
  },
  {
    id: 'STU-004',
    fullName: 'Roberto Uy',
    email: 'roberto@example.com',
    mobile: '09501234567',
    facebook: 'fb.com/robertouy',
    address: 'Talisay City, Cebu',
    experience: 'beginner',
    preferredSchedule: 'saturday',
    referralCode: 'PHIL-RUY004',
    sponsorCode: 'PHIL-MRS001',
    sponsorId: 'STU-001',
    paymentMethod: 'gcash',
    paymentReference: 'GC-444555666',
    status: 'completed',
    registeredAt: '2026-02-01T09:00:00Z',
    approvedAt: '2026-02-02T10:00:00Z',
    directReferrals: ['STU-009', 'STU-010', 'STU-011'],
    secondLevelReferrals: [],
    basicCourseStatus: 'completed',
    nextCourseStatus: 'completed',
    finalCourseStatus: 'completed',
    challengeTrainingStatus: 'passed',
    challengeProfirmStatus: 'passed',
    certificateIssued: true,
    certificateNumber: 'PMAC-2026-0001',
    certificateDate: '2026-05-01',
    awardStatus: 'paid',
    awardReference: 'AWD-001-2026',
    basicCourseProgress: 100,
    nextCourseProgress: 100,
    finalCourseProgress: 100,
  },
];

export const MOCK_PENDING_REGISTRATIONS: Registration[] = [
  {
    id: 'REG-001',
    fullName: 'Carlo Mendoza',
    email: 'carlo@example.com',
    mobile: '09611234567',
    facebook: 'fb.com/carlomendoza',
    address: 'Consolacion, Cebu',
    experience: 'beginner',
    preferredSchedule: 'wednesday',
    sponsorCode: 'PHIL-MRS001',
    paymentMethod: 'gcash',
    paymentReference: 'GC-777888999',
    status: 'pending',
    submittedAt: '2026-05-28T15:30:00Z',
  },
  {
    id: 'REG-002',
    fullName: 'Luz Fernandez',
    email: 'luz@example.com',
    mobile: '09721234567',
    facebook: 'fb.com/luzfernandez',
    address: 'Liloan, Cebu',
    experience: 'none',
    preferredSchedule: 'saturday',
    sponsorCode: '',
    paymentMethod: 'bank_transfer',
    paymentReference: 'BT-112233445',
    status: 'pending',
    submittedAt: '2026-05-27T10:00:00Z',
  },
];

export const MOCK_CONTACT_MESSAGES: ContactMessage[] = [
  {
    id: 'MSG-001',
    name: 'Pedro Garcia',
    email: 'pedro@example.com',
    mobile: '09831234567',
    subject: 'Workshop Schedule Inquiry',
    message: 'I would like to know more about the free workshop schedule this coming Saturday.',
    submittedAt: '2026-05-28T12:00:00Z',
    status: 'new',
  },
  {
    id: 'MSG-002',
    name: 'Elena Torres',
    email: 'elena@example.com',
    mobile: '09941234567',
    subject: 'Referral Code Question',
    message: 'Can I still use a referral code after I have already registered?',
    submittedAt: '2026-05-27T09:30:00Z',
    status: 'contacted',
  },
];

export const COURSES: Course[] = [
  {
    id: 'basic',
    title: 'Basic Forex Trading Course',
    description: 'Learn forex fundamentals, market structure, candlestick basics, support and resistance, and trading psychology introduction.',
    requiredForUnlock: 'Active subscription ($100)',
    lessons: [
      { id: 'b1', title: 'Introduction to Forex Markets', duration: '45 min', completed: true, type: 'video' },
      { id: 'b2', title: 'Understanding Currency Pairs', duration: '38 min', completed: true, type: 'video' },
      { id: 'b3', title: 'Candlestick Chart Basics', duration: '52 min', completed: true, type: 'video' },
      { id: 'b4', title: 'Support and Resistance Levels', duration: '41 min', completed: false, type: 'video' },
      { id: 'b5', title: 'Risk Management Fundamentals', duration: '35 min', completed: false, type: 'pdf' },
      { id: 'b6', title: 'Trading Psychology Introduction', duration: '30 min', completed: false, type: 'video' },
      { id: 'b7', title: 'Basic Course Assessment', duration: '20 min', completed: false, type: 'quiz' },
    ],
  },
  {
    id: 'next',
    title: 'Technical Analysis Training',
    description: 'Master technical analysis, entry/exit planning, trend confirmation, risk management, and trading journal setup.',
    requiredForUnlock: '3 direct paid referrals',
    lessons: [
      { id: 'n1', title: 'Advanced Chart Patterns', duration: '55 min', completed: false, type: 'video' },
      { id: 'n2', title: 'Indicators and Oscillators', duration: '48 min', completed: false, type: 'video' },
      { id: 'n3', title: 'Entry and Exit Strategies', duration: '60 min', completed: false, type: 'video' },
      { id: 'n4', title: 'Trend Confirmation Methods', duration: '44 min', completed: false, type: 'video' },
      { id: 'n5', title: 'Setting Up Your Trading Journal', duration: '25 min', completed: false, type: 'pdf' },
      { id: 'n6', title: 'Technical Analysis Assessment', duration: '20 min', completed: false, type: 'quiz' },
    ],
  },
  {
    id: 'final',
    title: 'Advanced Trading Mentorship',
    description: 'Advanced trading planning, strategy refinement, risk control, trading routine, and challenge preparation.',
    requiredForUnlock: '3x3 referral network completion',
    lessons: [
      { id: 'f1', title: 'Advanced Trading Strategy Development', duration: '65 min', completed: false, type: 'video' },
      { id: 'f2', title: 'Professional Risk Control', duration: '50 min', completed: false, type: 'video' },
      { id: 'f3', title: 'Building a Trading Routine', duration: '42 min', completed: false, type: 'video' },
      { id: 'f4', title: 'Challenge Preparation Guide', duration: '38 min', completed: false, type: 'pdf' },
      { id: 'f5', title: 'Final Mentorship Assessment', duration: '30 min', completed: false, type: 'quiz' },
    ],
  },
];

export function generateReferralCode(name: string): string {
  const initials = name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 3);
  const random = Math.random().toString(36).substring(2, 7).toUpperCase();
  return `PHIL-${initials}${random}`;
}
